apiVersion: apps/v1
kind: Deployment
metadata:
  name: murti
  labels:
    app: bhagwan 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bhagwan
  template:
    metadata:
      labels:
        app: bhagwan
    spec:
      containers:
      - name: shiva
        image: yanup30/node80
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: murti
spec:
  selector:
    app: bhagwan
  type: LoadBalancer
  ports:
  - port: 8080
